name: Odoo Code Quality Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Linters
        run: |
          pip install flake8 pylint pylint-odoo

      - name: Run Flake8
        run: flake8 .

      - name: Run Pylint with Odoo plugin
        run: pylint --load-plugins=pylint_odoo .

      - name: MERGE Histories (Local Git Step)
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          REPO_TOKEN: ${{ secrets.TOKEN_GH }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          TARGET_REPO_URL="https://github.com/cybrodevelopers/centralized-base_modules.git"
          git remote add target_repo $TARGET_REPO_URL

          echo "Fetching target repository main branch..."
          git fetch https://x-access-token:${REPO_TOKEN}@github.com/cybrodevelopers/centralized-base_modules.git main:target_repo_main

          git checkout $GITHUB_SHA

          echo "Merging target_repo_main into current commit..."
          git merge -X ours target_repo_main --no-ff --allow-unrelated-histories -m "Merge from centralized-dev after successful linting of $GITHUB_SHA"

      - name: PUSH to External Repo (Dedicated Action)
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GH }}
          repository: cybrodevelopers/centralized-base_modules
          branch: main
          force: true
          tags: false
